### ISSUE TITLE
Could not found API documentation 

### ISSUE THREAD

**Issue by Gujarats** [tokopedia/logging#3]
I tried to visit the docs :  https://godoc.org/gopkg.in/tokopedia.com/logging.v1 but not found.
 
I was kinda curious what's the different between package [log](https://golang.org/pkg/log/) in go and this one?

**Comment by wendyadi** [comment]
CMIIW

@Gujarats with this package you can specify where your application should redirect stdout and stderr with `-l` (for stdout) and `-e` (stderr) flag. 

```
./yourgoapp -l stdout.log -e stderr.log
```
is similar with
```
./yourgoapp 1>stdout.log 2>stderr.log
```

And also this package provide signal interaction with logrotate. The proper flow is everytime logrotate rotates the log, you set the logrotate to send `SIGHUP` to your app. Your app listen and then start to write to the new file created by logorotate.

https://github.com/tokopedia/logging/blob/v1.1/init.go#L39

However there is still some issues. When rotation happen, the app doesn't write to the new file.

https://github.com/tokopedia/logging/issues/1

**Comment by Gujarats** [comment]
do you know where the exact link for the documentation?

**Comment by Gujarats** [comment]
I've create a pull request for this issue : https://github.com/tokopedia/logging/pull/5

**Comment by qzaidi** [comment]
merged
